### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by be2slow** [josephschmitt/alexa-libby#30]
I've attempted to set this up, and I know the instructions are outdated, however I think I got it all squared away - except it isn't working.

When I test the skill, I get the error 'An exception occurred while dispatching the request to the skill'. I believe the issue is with the Lambda function itself, and I noticed the following in the logs:

Unable to import module 'index': Error
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

Any thoughts?

**Comment by be2slow** [comment]
And....the issue was because I zipped the folder and uploaded that, instead of zipping the contents.
